pin mdns component to avoid catatropic compilation
We'll have to revisit this soon to permit an upgrade to future versions,
but for now, I've pinned our dependency espressif/mdns to version 1.2.4.

Previously, we'd allowed >= 1.2.0, which encouraged, or at least allowed
upgrades. Unfortunately, 1.2.5 has some serious issue in our
build.  (See below).

I'll mark a low-priority issue to keep track of future upgrades, and in
the meantime, hope the presently working version is acceptable.

```
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/seeed_xiao_esp32c3.html
PLATFORM: Espressif 32 (6.5.0) > Seeed Studio XIAO ESP32C3
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-espidf @ 3.50102.240122 (5.1.2)
 - tool-cmake @ 3.16.4
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - tool-ninja @ 1.7.1
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0)
 - toolchain-riscv32-esp @ 12.2.0+20230208
Reading CMake configuration...
-- Found Git: /usr/bin/git (found version "2.43.2")
-- git rev-parse returned 'fatal: not a git repository (or any of the parent directories): .git'
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/jeff/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc
-- Check for working C compiler: /home/jeff/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc
-- Check for working C compiler: /home/jeff/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/jeff/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-g++
-- Check for working CXX compiler: /home/jeff/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32c3
Solving dependencies requirements
........Updating lock file at /home/jeff/Dropbox/workspace/motes/SOTAcat/dependencies.lock
Processing 2 dependencies:
[1/2] espressif/mdns (1.2.5)
[2/2] idf (5.1.2)
-- Configuring incomplete, errors occurred!
See also "/home/jeff/Dropbox/workspace/motes/SOTAcat/.pio/build/seeed_xiao_esp32c3/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any of the parent directories): .git
CMake Error at /home/jeff/.platformio/packages/framework-espidf/tools/cmake/component.cmake:250 (message):
  ERROR: 2 problems were found in the manifest file
  /home/jeff/Dropbox/workspace/motes/SOTAcat/managed_components/espressif__mdns/idf_component.yml:

  Invalid manifest format

  Unknown keys: repository_info

  SUGGESTION: This component may be using a newer version of the component
  manager.

  You can try to update the component manager by running:

      /home/jeff/.platformio/penv/.espidf-5.1.2/bin/python -m pip install --upgrade idf-component-manager

Call Stack (most recent call first):
  /home/jeff/.platformio/packages/framework-espidf/tools/cmake/build.cmake:574 (__component_get_requirements)
  /home/jeff/.platformio/packages/framework-espidf/tools/cmake/project.cmake:547 (idf_build_process)
  CMakeLists.txt:3 (project)

 [FAILED] Took 2.61 seconds

Environment         Status    Duration
------------------  --------  ------------
seeed_xiao_esp32c3  FAILED    00:00:02.606
 1 failed, 0 succeeded in 00:00:02.606

PIOCompilation exited abnormally with code 1 at Wed Mar  6 21:49:41
```